### ISSUE TITLE
[SOLVED] Pressure-Plate configuration

### ISSUE THREAD

**Issue by SlimeDog** [Block2Block/HubParkour-Legacy#3]
IMHO, the accepted 1.13.2 values should be the following (ie., minecraft:{itemName}):
```
ACACIA_PRESSURE_PLATE
BIRCH_PRESSURE_PLATE
DARK_OAK_PRESSURE_PLATE
HEAVY_WEIGHTED_PRESSURE_PLATE
JUNGLE_PRESSURE_PLATE
LIGHT_WEIGHTED_PRESSURE_PLATE
OAK_PRESSURE_PLATE
SPRUCE_PRESSURE_PLATE
STONE_PRESSURE_PLATE
```
rather than the current:
```
Gold
Iron
Stone
Wood
```
In addition, it would be nice to be able to use multiple types for checkpoints; for example:
```
Settings:
    Pressure-Plates:
        Start: LIGHT_WEIGHTED_PRESSURE_PLATE
        Checkpoint:
        - BIRCH_PRESSURE_PLATE
        - JUNGLE_PRESSURE_PLATE
        End: HEAVY_WEIGHTED_PRESSURE_PLATE
```
BTW, /parkour reload appears to not change the configured values in-game. Restart is required.
